name: 22bot

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */6 * * *'  # every 6 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 370  # 6h + buffer
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Load environment variables from .env
        run: |
          set -a
          source .env
          set +a

      - name: Validate environment variables
        run: |
          REQUIRED_VARS=("MC_PASSWORD" "STORAGE_REPO_TOKEN" "MAIN_REPO_PAT")
          PLACEHOLDERS=("ghp_yourtokenhere" "123456")  # Add any placeholder values you want to detect

          for VAR in "${REQUIRED_VARS[@]}"; do
            VAL="${!VAR}"
            if [ -z "$VAL" ]; then
              echo "❌ Error: $VAR is empty"
              exit 1
            fi
            for PH in "${PLACEHOLDERS[@]}"; do
              if [ "$VAL" = "$PH" ]; then
                echo "❌ Error: $VAR is still set to placeholder ($PH)"
                exit 1
              fi
            done
          done

      - name: Clone archive repo (restore previous data)
        run: |
          git clone "https://x-access-token:${STORAGE_REPO_TOKEN}@github.com/Damix-hash/.22-archive.git" archive-repo
          mkdir -p output
          cp -r archive-repo/output/* output/ || echo "No previous output files to restore"

      - name: Run bot for 5 hours 59 minutes then stop
        run: |
          npm start &
          BOT_PID=$!
          echo "Bot started with PID $BOT_PID"
          sleep $((5 * 3600 + 59 * 60))  # 5h 59m
          echo "Stopping bot"
          kill $BOT_PID
          wait $BOT_PID || true

      - name: Copy output files to archive repo (update archive)
        run: |
          mkdir -p archive-repo/output
          cp -r output/* archive-repo/output/ || echo "No output files to copy"

      - name: Commit and push to archive repo
        run: |
          cd archive-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Autosave bot_data.json from bot run [ci skip]" || echo "No changes to commit"
          git push origin main

      - name: Re-trigger this workflow (self-restart)
        run: |
          echo "Re-triggering workflow..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${MAIN_REPO_PAT}" \
            https://api.github.com/repos/Damix-hash/.22/actions/workflows/bot.yml/dispatches \
            -d '{"ref":"main"}'
